SPT-1347 DebugScreen, поправить фичу логгера
surfstudio/debug-screen-ios pull request #26
Opened 2023-05-19 12:13 UTC by AdmiralBizon

# Problem

При использовании логгера пропадали все сообщения из консоли и в файл также не попадали.

# What is done

- Исправлена ошибка с выводом сообщений в файл и обратно в консоль (добавил еще один `Pipe`, который при обработке вернет данные в консоль Xcode)
- Обновлен интерфейс самого `LogCatcherService`: для запуска сделал единый метод `start()`, метод для очистки файла логов также сделан публичным, добавлены публичные свойства `stdOutCatchingEnabled` и `stdErrCatchingEnabled`, в зависимости от значений которых можно управлять выводом в файл (писать туда только ошибки, только информационные сообщения или все вместе)
- Изменен интерфейс протокола `FeatureToggleActionsProvider`: удален метод `handleAction`
- Изменена модель `FeatureToggleModel`: добавлено свойство `block`, в которое можно поместить код, который будет вызван после переключения свитчера
- Добавлены модули для отображения простых алертов с заданным текстом и просмотра локальных файлов по переданному адресу
- На Debug экран добавлена секция управления логгером
- Обновлен Example проект в соответствии с внесенными изменениями
- Обновлен файл Readme - [тут](https://github.com/surfstudio/debug-screen-ios/tree/SPT-1347-log-catcher-update)

# What to look for

- Для просмотра файлов используется `QLPreviewController`, который при открытии в консоли может ругаться на какие-то констрейнты. Погуглил на этот счет - пишут, что это нормальная ситуация, приколы самого этого контроллера и можно не обращать внимания.
- Если обернуть этот контроллер в navigation, то ругаться перестанет, но появляются другие приколы по типу мигающих кнопок в навигейшене и тулбаре, а также с удалением из памяти после закрытия. Докопаться до того, почему так происходит не получилось, поэтому оставил вариант без навигейшена - там таких проблем нет)
- В логгер добавил исключение для ошибок о констрейнтах (там обычно вылетает огромная простыня и писать ее в файл наверное не имеет большого смысла - вряд ли такие ошибки будут интересны, как мне кажется) - они игнорятся и не пишутся в файл (но в консоли отображаются).

# How to check

- Запустить Example
- Зайти на Debug экран
- Открыть файл с логами, проверить, что изначально он пустой
- Включить переключатели для записи информации и ошибок в логи
- Понажимать на разные экшены, которые будут печатать текст в консоль
- Открыть файл и убедиться, что логи попали и туда
- Попробовать очистить файл, убедиться, что операция выполнилась успешно

2023-05-29 15:53 UTC, chausovSurfStudio requested changes
кажется тут что-то надо будет поменять)

на интерфейсные вещи можешь забить, все равно потом будут идти задачи на его изменение, но остальные комменты погляди (в частности, по умолчанию фича-тоглам true поставить)

2023-05-29 15:53 UTC, chausovSurfStudio commented on DebugScreen.xcodeproj/project.pbxproj
> +				B2610E1E2A16D90600509FA1 /* CommonFlow */,
а может просто эти две новый папки в корень вынести, но то есть во Flows, рядышком с MainScreen? или задумка какая-то была?)

2023-05-29 15:53 UTC, chausovSurfStudio commented on DebugScreen/Resources/Strings/en.lproj/Localizable.strings
> +"MainPresenter.Logger.ClearLogs.success" = "Clear complete";
отметь себе на будущее - надо будет потом еще внимательнее поглядеть, что с локалью. Потому что у меня на личном девайсе стоит русский, а вот это сообщение - показывается на английском (именно в example-проекте, на шаблоне сейчас запустил - там всё окъ)

2023-05-29 15:53 UTC, chausovSurfStudio commented on DebugScreen/Flows/MainScreen/Presenter/MainModulePresenter.swift
> +    func createLoggerSection() -> TableSection {
меня эт немного смущает) на данном этапе пойдет, потому что ты все равно сейчас в текущих задачах все переписывать будешь, но вообще хотелось бы какой-то гибкости - чтобы была возможность показывать эту секцию или не показывать. Потому что сейчас она намертво зашивается, причем в самом начале дебаг-экрана, а гвоздями мы решили ничего тут больше не прибивать(

2023-05-29 15:53 UTC, chausovSurfStudio commented on DebugScreen/Services/LogCatcherService.swift
> +        logPath
надо бы договориться - пишем return в таких случаях или нет) а то сейчас он то есть, то нет...

2023-05-29 15:53 UTC, chausovSurfStudio commented on DebugScreen/Services/LogCatcherService.swift
> +        let keyWords = ["LayoutConstraints", "UIViewAlertForUnsatisfiableConstraints"]
упомяни эти ключевые слова обязательно в техдоке)) а то сюрприз будет тем, кто ожидает эти логи увидеть (а может... на это тоже свой featureToggle повесить?)

кстати о фича-тоглах - что думаешь, если по умолчанию будут записываться и info и ошибки? ну то есть ты программист ты хочешь снимать логи, стартуешь этот LogCatcher - наслаждаешься. И тебе не надо думать о том, чтобы еще какие-то фича-тогла менять, или просить поменять их пользователей

2023-05-29 16:16 UTC, AdmiralBizon commented on DebugScreen/Services/LogCatcherService.swift
> +        let keyWords = ["LayoutConstraints", "UIViewAlertForUnsatisfiableConstraints"]
В целом да, наверное удобнее если он по умолчанию будет все писать. По идее если тебе нужно словить определенный принт какой-то и ты не хочешь, чтобы логи с ошибками мешались в файле, можно будет отключить вывод ошибок на дебаг скрине и потом нужный кейс повторить. Короче эти переключатели могут понадобиться в каких-то редких ситуациях как будто бы. Может вообще тогда их убрать, как думаешь?

А насчет ключевых слов еще подумал, может сделать какую-то штуку в интерфейсе, где можно будет накидать список ключевых слов, логи с которыми не будут в файл записываться. Но не знаю, нужно ли вообще это или достаточно будет того, что игнорим сообщения о констрейнтах, а остальное пусть все пишется?

2023-05-29 16:30 UTC, chausovSurfStudio commented on DebugScreen/Services/LogCatcherService.swift
> +        logPath
давай писать return?) я старовер 😁

2023-05-29 16:31 UTC, chausovSurfStudio commented on DebugScreen/Services/LogCatcherService.swift
> +        let keyWords = ["LayoutConstraints", "UIViewAlertForUnsatisfiableConstraints"]
а кстати неплохая идея... blacklist - если слово есть в blacklist, то сообщение игнорируется

а где blacklist, там и whitelist - пишутся только слова, которые есть в whitelist, если whitelist не пуст))

2023-05-29 17:43 UTC, AdmiralBizon commented on DebugScreen/Services/LogCatcherService.swift
> +        let keyWords = ["LayoutConstraints", "UIViewAlertForUnsatisfiableConstraints"]
только я пока не могу придумать в каком виде это в UI лучше отрисовать. Из того, что в голову с ходу приходит - текстфилд для ввода и под ним табличка, которая будет обновляться после каждого добавления слова / фразы через текстфилд

2023-05-29 19:18 UTC, AdmiralBizon commented on DebugScreen/Resources/Strings/en.lproj/Localizable.strings
> +"MainPresenter.Logger.ClearLogs.success" = "Clear complete";
Проблема была в том, что в Example-проекте не была настроена локализация - поправил.

2023-05-30 08:53 UTC, chausovSurfStudio commented on DebugScreen/Services/LogCatcherService.swift
> +        let keyWords = ["LayoutConstraints", "UIViewAlertForUnsatisfiableConstraints"]
договорились сделать потом, пока - просто отразить в readme то, что логи про констрейнты пропускаются

2023-05-30 08:55 UTC, chausovSurfStudio approved these changes

2023-05-30 11:57 UTC, merged