[SPT-1471, SPT-1472] Изменение конфигурации и логики работы
surfstudio/debug-screen-ios pull request #28
Opened 2023-06-02 13:00 UTC by AdmiralBizon

# What is done

- Изменена структура библиотеки и логика работы с ней: теперь вместо работы через провайдеры необходимо использовать секции
- Добавлена возможность собирать секцию управления логгером из готовых компонентов (просто выбрав нужные и добавив их в массив без дополнительной обработки)
- В DebugScreenPresenterService добавлены публичные функции для открытия файла логов и показа алертов
- Обновлен Example-проект
- Обновлен Readme файл

# What to look for

- Этот ПР содержит сразу несколько задач. В итоге решил не отделять в отдельный ПР задачу по поддержке независимых экшенов, потому как она бы была очень маленькой. Больше бы ушло времени на то, чтобы вытащить эти кусочки из общего кода и ничего не сломать.
- Т.к. здесь много глобальных изменений, на проектах, которые пользуются этой библиотекой, после обновления Debug-экран сломается и нужно будет адаптировать их под новый интерфейс.

# How to check

- Запустить Example-проект -> Поиграться с дебаг экраном
- Почитать [обновленный Readme](https://github.com/surfstudio/debug-screen-ios/tree/SPT-1471-configuration-and-main-logic-rework)

2023-06-05 10:57 UTC, chausovSurfStudio requested changes
ага, смотри

в целом все круто, я тут особо даже не докапывался) давай только один момент поправим сразу. При смене сервера - обычно требуется скинуть какой-то локальный кеш, иногда стек навигации и даже в целом перезагрузить приложения. Сейча сервак меняется при смене значения в барабане. Давай сделаем отдельную подтверждающую кнопку? типа чтобы

- подкрутил нужное значение
- тапнул на кнопку
- сервер поменялся

2023-06-05 10:57 UTC, chausovSurfStudio commented on Example/Example/App/DebugScreenConfiguration/Models/DebugScreenAction.swift
> +    var title: String
тоже let можно оставить?

2023-06-05 10:57 UTC, chausovSurfStudio commented on Example/Example/App/DebugScreenConfiguration/Builders/CopiedTextSectionBuilder.swift
> +        return blocks
можно вот так вот)
```swift
return items.map { .copiedText(model: $0) }
```

2023-06-05 16:39 UTC, AdmiralBizon commented
Превьюшку (фото с симулятором), которое в readme отображается перенесу из внешнего файлообменника в репозиторий в следующем ПР - как раз буду описание редактировать.

2023-06-09 10:46 UTC, chausovSurfStudio approved these changes

2023-06-09 10:47 UTC, merged