SPT-1505 DebugScreen, интеграция темной темы
surfstudio/debug-screen-ios pull request #30
Opened 2023-06-20 18:47 UTC by AdmiralBizon

# What is done

- Добавлена поддержка темной темы
- Обновлен Example-проект
- Обновлено превью в Readme-файле

# How to check

- Запустить Example-проект --> Переключить тему --> Посмотреть, что все отображается корректно
- Посмотреть обновленное фото в [Readme](https://github.com/surfstudio/debug-screen-ios/tree/SPT-1505-dark-mode-support)

2023-06-21 14:53 UTC, chausovSurfStudio requested changes
маленькие правочки, в остальном вопросов нет, все круто)

2023-06-21 14:53 UTC, chausovSurfStudio commented on DebugScreen/Flows/MainScreen/View/Adapter/Cells/SwitcherCell/SwitcherCell.swift
> +        switcher.onTintColor = Colors.Buttons.Secondary.normalBackground
<img width="913" alt="Снимок экрана 2023-06-21 в 17 46 42" src="https://github.com/surfstudio/debug-screen-ios/assets/8776643/feffc714-dec1-4f1b-bede-dc05f6bcbae3">

а может этот цвет вообще не трогать у переключателя? а то он в темной теме белый на практически белом получается))

2023-06-21 14:53 UTC, chausovSurfStudio commented on DebugScreen/Resources/Images/Assets.swift
> +      internal static let primary = ColorAsset(name: "Text/primary")
напишу здесь, но комментарий не к этой строке)

а раз уж сюда добрался - давай может highlighted цвета для primary и secondary стилей кнопок сделаем более отличающимися от normal цвета? а то жмешь на кнопку - и непонятно, нажата она была или нет(

к Destructive стилю вопросов в этом плане нет))

2023-06-23 08:11 UTC, AdmiralBizon commented
- обновил main и highlighted цвета для кнопок - теперь видно когда она нажимается)
- для свитчера вернул стандартный цвет
- обновил example-проект

2023-06-23 08:56 UTC, chausovSurfStudio approved these changes

2023-06-23 08:56 UTC, merged